using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cysharp.Threading.Tasks;
using System;
using System.Threading;

public class GameState : MonoBehaviour
{
    [Tooltip("å¾…æ©Ÿæ™‚é–“")]
    [SerializeField] private float _overheadViewNum;
    [Header("å¾…æ©Ÿã—ãŸå¾Œä½•ç§’å¾Œãƒ‘ã‚ºãƒ«ç”»é¢ã‚’å‡ºã™ã‹")]
    [SerializeField] private float _puzzleActiveNum;
    [SerializeField] private GameObject _puzzleObj;
    [SerializeField] private GameObject _cinemachineObj;
    [SerializeField] private NewPlayerMove _playerMove;
    [SerializeField] private Timer _timer;
	[SerializeField] private AudioManager audioManager;
    private GameStateType _gameStateType = GameStateType.OverheadViewState;
    private Vector2 _outDirection = Vector2.up;
    //private WaitForSeconds _puzzleOutWait = new WaitForSeconds(0.01f);

    private void Start()
    {
        ChangeState(GameStateType.OverheadViewState);
    }

    private void Update()
    {

    }

    /// <summary>
    /// ï¿½Xï¿½eï¿½[ï¿½gï¿½ï¿½ÏXï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <param name="gameStateType"></param>
    public async void ChangeState(GameStateType gameStateType)
    {
        _gameStateType = gameStateType;
        await ChangeStateEvent();
    }

    /// <summary>
    /// ï¿½ÏXï¿½ï¿½ï¿½ê‚½ï¿½Xï¿½eï¿½[ï¿½gï¿½É”ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½ï¿½
    /// </summary>
    /// <returns></returns>
    public async UniTask ChangeStateEvent()
    {
        if (_gameStateType == GameStateType.OverheadViewState)
        {
            await UniTask.Delay(TimeSpan.FromSeconds(_overheadViewNum));
            _cinemachineObj.SetActive(false);
            await UniTask.Delay(TimeSpan.FromSeconds(_puzzleActiveNum));
            ChangeState(GameStateType.PuzzleState);
        }
        else if (_gameStateType == GameStateType.PuzzleState)
        {

            Debug.Log("ï¿½pï¿½Yï¿½ï¿½ï¿½Å‚ï¿½");
            _puzzleObj.SetActive(true);
			audioManager.PuzzleBGM();

		}
        else if (_gameStateType == GameStateType.MainGameState)
        {
            if (_puzzleObj) 
            {
                _puzzleObj.SetActive(false);
            }
            else 
            {
               var obj = GameObject.FindWithTag("GameController");
               obj.SetActive(false);
            }
            //Playerï¿½ğ“®‚ï¿½ï¿½ï¿½ï¿½nï¿½ß‚ï¿½æ‚¤ï¿½ÈŠÖï¿½ï¿½ï¿½ï¿½Ä‚ï¿½
            if (_playerMove)
            {
                _playerMove.CanMove = true;
            }
            else 
            {
                _playerMove = GameObject.FindObjectOfType<NewPlayerMove>();
                _playerMove.CanMove = true;
            }
            
            _timer.Puzzle = true;
			// audioManager.MainBGM();
        }
    }

    /// <summary>
    /// ï¿½pï¿½Yï¿½ï¿½ï¿½ï¿½ï¿½eï¿½Bï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
    /// </summary>
    /// <returns></returns>
    private void PuzzleOut()
    {
        RectTransform _currentPosition = (RectTransform)_puzzleObj.transform;
        float currentTime = 0f;

        while (((RectTransform)_puzzleObj.transform).position.y >= _currentPosition.position.y)
        {
            if (currentTime >= 0.01f)
            {
                ((RectTransform)_puzzleObj.transform).Translate(_outDirection);
                currentTime = 0f;
            }

            currentTime += Time.deltaTime;
        }
    }
}

public enum GameStateType
{
    OverheadViewState,
    PuzzleState,
    MainGameState,
}
